# Generated by Django 4.0.2 on 2022-02-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='branches',
        ),
        migrations.AddField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(to='courses.Branch'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='contacts',
        ),
        migrations.AddField(
            model_name='course',
            name='contacts',
            field=models.ManyToManyField(to='courses.Contact'),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
